# Generated by Django 6.0.5 on 2026-05-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='user_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
